"""Изменение типа поля rate на Float

Revision ID: 0bc798658be4
Revises: 8a6082e1efa5
Create Date: 2025-04-20 06:55:30.534728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc798658be4'
down_revision = '8a6082e1efa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax', schema=None) as batch_op:
        batch_op.alter_column('rate',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax', schema=None) as batch_op:
        batch_op.alter_column('rate',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
